School/Models/Gallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace School.Models
{
    public class Gallery
    {
        [Display(Name = "شناسه")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string Id { get; set; }

        [Display(Name = "عکس")]
        public string Image { get; set; }
    }
}

School/Areas/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Helpers;
using School.Models;
using School.Models.Helpers;
using School.Models.Helpers.OptionEnums;

namespace School.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class GalleryController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment _env;

        public GalleryController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        [HttpGet]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index()
        {
            ViewBag.Path = "/upload/thumbnailimage/";
            return View(await _context.Galleries.ToListAsync());
        }

        [HttpGet]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddEdit(string id)
        {
            var gallery = await _context.Galleries.FirstOrDefaultAsync(c => c.Id == id);
            if (gallery != null)
            {
                return PartialView("AddEdit", gallery);
            }

            return PartialView("AddEdit", new Gallery());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit(string id, Gallery model, IEnumerable<IFormFile> files, string imgName)
        {
            if (ModelState.IsValid)
            {
                var upload = Path.Combine(_env.WebRootPath.Replace("\\", "/") + Helper.NormalImagePath);
                foreach (var file in files)
                {
                    if (file != null && file.Length > 0)
                    {
                        var filename = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                        await using (var fs = new FileStream(Path.Combine(upload, filename), FileMode.Create))
                        {
                            await file.CopyToAsync(fs);
                            model.Image = filename;
                        }
                        var image = new ImageResizer();
                        image.Resize(upload + filename, _env.WebRootPath + Helper.ThumbnailImagePath + filename);
                    }
                }

                if (String.IsNullOrWhiteSpace(id))
                {

                    if (model.Image == null)
                    {
                        model.Image = "defaultpic.png";
                    }
                    _context.Add(model);
                    await _context.SaveChangesAsync();
                    TempData["Notification"] = Notification.ShowNotif(MessageType.Add, ToastType.Green);
                    return Json(new { Status = "success" });
                }

                if (model.Image == null)
                {
                    model.Image = imgName;
                }

                _context.Update(model);
                await _context.SaveChangesAsync();

                TempData["Notification"] = Notification.ShowNotif(MessageType.Edit, ToastType.Blue);
                return Json(new { Status = "success" });
            }

            var list = new List<string>();
            foreach (var validation in ViewData.ModelState.Values)
            {
                list.AddRange(validation.Errors.Select(error => error.ErrorMessage));
            }
            return Json(new { Status = "error" });
        }

        [HttpGet]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var gallery = await _context.Galleries.SingleOrDefaultAsync(a => a.Id == id);
            if (gallery == null)
            {
                return RedirectToAction("Index");
            }

            return PartialView("Delete", "تصویر گالری ");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, string redirectUrl)
        {
            if (ModelState.IsValid)
            {
                {
                    var model = await _context.Galleries.SingleOrDefaultAsync(b => b.Id == id);

                    var sourcePath = Path.Combine(_env.WebRootPath.Replace("\\", "/") + Helper.NormalImagePath, model.Image);
                    if (System.IO.File.Exists(sourcePath))
                    {
                        System.IO.File.Delete(sourcePath);
                    }

                    var sourcePath2 = Path.Combine(_env.WebRootPath.Replace("\\", "/") + Helper.ThumbnailImagePath, model.Image);
                    if (System.IO.File.Exists(sourcePath2))
                    {
                        System.IO.File.Delete(sourcePath2);
                    }

                    _context.Remove(model);
                    await _context.SaveChangesAsync();
                }

                TempData["Notification"] = Notification.ShowNotif(MessageType.Delete, ToastType.Red);
                return PartialView("_SuccessfulResponse", redirectUrl);
            }

            TempData["Notification"] = Notification.ShowNotif(MessageType.DeleteError, ToastType.Red);
            return RedirectToAction("Index");
        }
    }
}

School/Areas/Admin/Views/Gallery/AddEdit.cshtml
@model School.Models.Gallery

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, School

<form method="post" enctype="multipart/form-data">

    @*header*@
    @if (!String.IsNullOrWhiteSpace(Model.Id))
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش گالری تصاویر" })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن گالری تصاویر" })
    }


    @*body*@
    <div class="modal-body form-horizontal">

        <div class="row">
      
            <div class="form-group">
                <label asp-for="Image" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input required="required" type="file" id="files" name="files" multiple />
                </div>
                @if (!String.IsNullOrWhiteSpace(Model.Id))
                {
                    <input type="hidden" name="Imgename" value="@Model.Image" />
                }
            </div>

            <input type="hidden" asp-for="Id" class="form-control" />

            <input type="hidden" name="redirectUrl" value="@Url.Action("index","Gallery")" />

        </div>
    </div>

    @*footer*@
    @if (!String.IsNullOrWhiteSpace(Model.Id))
    {
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal" value="برگشت">برگشت</button>
            <input type="submit" id="submitdata" class="btn btn-success" value="ویرایش تصویر" />
        </div>

    }
    else
    {
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal" value="برگشت">برگشت</button>
            <input type="submit" id="submitdata" class="btn btn-success" value="افزودن تصویر" />
        </div>

    }


</form>

<script>
    $(document).on('click', '#submitdata', function (evt) {
        evt.preventDefault();
        var fileUpload = $("#files").get(0);
        var files = fileUpload.files;
        var data = new FormData();
        for (var i = 0; i < files.length; i++) {
            data.append('files', files[i]);

        }
        $('input').each(function (x, y) {
            data.append($(y).attr('name'), $(y), val());

        });
        $.ajax({
            type: "POST",
            url: '@Url.Action("AddEdit", "Gallery", new { Areas = "Admin" })',
            contentType: false,
            processData: false,
            data: data

        }).done(function (res) {
            if (res.status === "success") {
                alert(res.message);
            }
            else {
                alert("در ثبت اطلاعات مشکلی وجود دارد");
                
                window.location.href = '@Url.Action("Index", "Gallery")';

            }
        }).fail(function (xhr, b, error) {

            alert(error);
        });

    });

</script>

School/Areas/Admin/Views/Gallery/Delete.cshtml
@model string

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, School

<form asp-controller="Gallery" asp-action="Delete">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف تصویر" })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirectUrl" value="@Url.Action("Index","Gallery")" />

    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف" })

</form>

School/Areas/Admin/Views/Gallery/Index.cshtml
@model IEnumerable<Gallery>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, School

@{
    ViewData["Title"] = "گالری تصاویر";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>@ViewBag.Title</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showBrand" data-toggle="modal" asp-action="AddEdit"
                                   data-target="#modal-action">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن تصویر جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int Count = 0;
                                foreach (var item in Model)
                                {
                                    Count++;
                                    <tr>
                                        <td>@Count</td>
                                        <td>
                                            <img src="@ViewBag.Path@item.Image" />
                                        </td>


                                        <td>
                                            <a class="btn btn-info" id="editagency" data-toggle="modal" asp-action="AddEdit"
                                               data-target="#modal-action" asp-route-id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>


                                            <a class="btn btn-danger" id="editagency" data-toggle="modal" asp-action="Delete"
                                               data-target="#modal-action" asp-route-id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/images/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@await Html.PartialAsync("_Modal", new BootstrapModel { Id = "modal-action", Size = ModalSize.Medium })

@section Scripts{

    <script>
        $(document).on('click', '#submitdata', function (evt) {
            evt.preventDefault();
            var fileUpload = $("#files").get(0);
            var files = fileUpload.files;
            var data = new FormData();
            for (var i = 0; i < files.length; i++) {
                data.append('files', files[i]);

            }
            $('input,select').each(function (x, y) {
                data.append($(y).attr('name'), $(y).val());

            });
            $.ajax({
                type: "post",
                url: '@Url.Action("AddEdit", "Gallery", new { Area = "Admin" })',
                contentType: false,
                processData: false,
                data: data

            }).done(function (res) {
                if (res.status === "success") {
                    window.location.href = '@Url.Action("Index", "Gallery")';
                }
                else {
                    $.each(res.error, function (a, b) {
                        alert(b);

                    });

                }
            }).fail(function (xhr, b, error) {

                alert(error)
            });

        });

    </script>

}